[build-system]
requires = ["setuptools >= 65", "wheel >= 0.38"]
build-backend = "setuptools.build_meta"

[project]
name = "mems"
version = "0.1.0"
dependencies = ["colorama==0.4.6", "kiutils==1.4.0", "termcolor==2.2.0", "requests==2.28.2"]
scripts = {mems = "mems.mems:main"}

[project.optional-dependencies]
dev = ["mypy", "ruff", "black"]

[tool.ruff]
select = ["E", "F", "N", "B", "A", "RET"]
line-length = 120
target-version = "py38"

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
